CREATE OR REPLACE TRIGGER T1 
AFTER INSERT OR UPDATE OF AMOUNT ON FALL22_S003_15_MEMBERS_RETURNS_BOOKS 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE AMOUNT_DIFF NUMBER;   
BEGIN
    AMOUNT_DIFF :=  :NEW.AMOUNT - :OLD.AMOUNT;
    DBMS_OUTPUT.PUT_LINE('The old amount was: ' || :OLD.AMOUNT);
    DBMS_OUTPUT.PUT_LINE('The updated amount is: ' || :NEW.AMOUNT);
    DBMS_OUTPUT.PUT_LINE('The difference amount is: ' || AMOUNT_DIFF);
END;




SET SERVEROUTP ON;
